---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    # - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu2004
    # - MOLECULE_DISTRO: ubuntu1804
    # - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    # - MOLECULE_DISTRO: debian9
    # - MOLECULE_DISTRO: debian8

install:
  - pip install molecule 'molecule[docker]' yamllint ansible-lint docker

script:
  - molecule test
