---
# configure tasks file for ansible-role-tomcat

- name: "Configure : Set verions specific switches"
  set_fact:
    tomcat_template_server: "tomcat-server-{{ tomcat_major_version }}.xml.j2"
    tomcat_template_users: "tomcat-users-{{ tomcat_major_version }}.xml.j2"

- name: "Configure : Set user roles"
  set_fact:
    tomcat_user_roles: "{{ (tomcat_user_roles + item.roles.split(',')|list)|unique }}"
  no_log: True
  with_items:
    - "{{ tomcat_users }}"

- name: "Configure : Build config files"
  template:
    src: "{{ item.src }}"
    dest: "{{ tomcat_catalina_base }}/conf/{{ item.dest }}"
    owner: root
    group: "{{ tomcat_group }}"
    mode: "{% if tomcat_permissions_production %}0640{% else %}0644{% endif %}"
  loop:
    - src: "{{ tomcat_template_server }}"
      dest: server.xml
    - src: "{{ tomcat_template_users }}"
      dest: tomcat-users.xml
  notify: restart tomcat

- name: "Configure : Configure access to Manager/host-manager apps"
  template:
    src: "{{ item.src }}"
    dest: "{{ tomcat_catalina_base }}/{{ item.dest }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: "{% if tomcat_permissions_production %}0640{% else %}0644{% endif %}"
  loop:
    - src: "{{ tomcat_template_manager_context }}"
      dest: webapps/manager/META-INF/context.xml
    - src: "{{ tomcat_template_host_manager_context }}"
      dest: webapps/host-manager/META-INF/context.xml
  notify: restart tomcat

- name: "Configure : Tomcat Systemd service"
  when:
    - ansible_service_mgr == "systemd"
    - tomcat_service_enabled
  block:
    - name: "Configure : Install Systemd service"
      template:
        src: "{{ tomcat_template_systemd_service }}"
        dest: /etc/systemd/system/{{ tomcat_service_name }}.service
        mode: "0644"
      notify: restart tomcat

    - name: "Configure : Enable Tomcat Systemd service"
      systemd:
        name: "{{ tomcat_service_name }}"
        enabled: "{% if tomcat_service_enabled %}yes{% else %}no{% endif %}"
        daemon_reload: yes

- name: "Configure : Tomcat SysVinit service"
  when:
    - ansible_service_mgr == "sysvinit"
    - tomcat_service_enabled
  block:
    - name: "Configure : Install SysVinit service"
      template:
        src: "{{ tomcat_template_sysvinit_service }}"
        dest: "/etc/init.d/{{ tomcat_service_name }}"
        mode: "0755"

    - name: "Configure : Enable Tomcat SysVinit service"
      service:
        name: "{{ tomcat_service_name }}"
        enabled: "{% if tomcat_service_enabled %}yes{% else %}no{% endif %}"
