---
- name: "Permissions : Set non-prod permissions"
  when:
    - tomcat_installed is changed or tomcat_permissions_ensure_on_every_run
    - not tomcat_permissions_production
  block:
    - name: "Permissions : Set owner and group for non-production installation"
      file:
        path: "{{ tomcat_path }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        recurse: yes

    - name: "Permissions : Set directories permissions for non-production installation"
      command: find {{ tomcat_path }} -type d -exec chmod -c 2775 {} \;
      register: find_chmod_result
      changed_when: 'find_chmod_result.stdout | length > 0'

    - name: "Permissions : Set files permissions for non-production installation"
      command: find {{ tomcat_path }} -type f -not -name "*.sh" -exec chmod -c 0664 {} \;
      register: find_chmod_result
      changed_when: 'find_chmod_result.stdout | length > 0'

- name: "Permissions : Set non-prod permissions"
  when:
    - tomcat_installed is changed or tomcat_permissions_ensure_on_every_run
    - tomcat_permissions_production
  block:
    - name: "Permissions : Set root directory owner/group for production installation"
      file:
        path: "{{ tomcat_path }}"
        owner: root
        group: "{{ tomcat_group }}"

    - name: "Permissions : Set recursively directories owner/group for production installation"
      file:
        path: "{{ tomcat_path }}/{{ item }}"
        owner: root
        group: "{{ tomcat_group }}"
        recurse: yes
      with_items:
        - bin
        - conf
        - lib

    - name: "Permissions : Set recursively directories owner/group for production installation"
      file:
        path: "{{ tomcat_path }}/{{ item }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        recurse: yes
      with_items:
        - logs
        - temp
        - work

    - name: "Permissions : Set recursively webapps directory owner/group for production installation"
      file:
        path: "{{ tomcat_path }}/webapps"
        owner: "{% if tomcat_webapps_auto_deployment %}{{ tomcat_user }}{% else %}root{% endif %}"
        group: "{{ tomcat_group }}"
        recurse: yes

    - name: "Permissions : Set directories permissions for production installation"
      command: find {{ tomcat_path }} -type d -exec chmod -c 2750 {} \;
      register: find_chmod_result
      changed_when: 'find_chmod_result.stdout | length > 0'

    - name: "Permissions : Set files permissions for production installation (1/2)"
      command: find {{ tomcat_path }} -type f -not -name "*.sh" -exec chmod -c 0640 {} \;
      register: find_chmod_result
      changed_when: 'find_chmod_result.stdout | length > 0'

    - name: "Permissions : Set files permissions for production installation (2/2)"
      command: find {{ tomcat_path }} -type f -name "*.sh" -exec chmod -c 0750 {} \;
      register: find_chmod_result
      changed_when: 'find_chmod_result.stdout | length > 0'











































