---
- name: Converge
  hosts: all
  vars:
    tomcat_permissions_production: True

  roles:
    - geerlingguy.java

  tasks:
    - name: "Include ansible-role-tomcat"
      include_role:
        name: "ansible-role-tomcat"
