---
- name: Converge
  hosts: all

  pre_tasks:
    - name: "Converge : Update apt cache for APT systems"
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - geerlingguy.java

  tasks:

    - name: "Converge : Include ansible-role-tomcat"
      include_role:
        name: "ansible-role-tomcat"
