---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    tomcat_service_enabled: True
    tomcat_service_name: tomcat
    tomcat_port_connector: 8080

  roles:
    - vantaworks.goss

  tasks:

    - name: "Verify : Add goss tests file"
      copy:
        src: goss.yml
        dest: /goss.yml
        mode: 644

    - name: "Verify : Execute goss tests"
      command: "goss -g /goss.yml validate --format rspecish"
      register: test_results

    - name: "Verify : Show results"
      debug:
        msg: "{{ test_results.stdout_lines }}"

    - name: "Verify : Fail when tests fail"
      fail:
        msg: "Goss failed to validate"
      when: test_results.rc != 0
