---
service:
  tomcat:
    enabled: true
    running: true
user:
  tomcat:
    exists: true
    uid: 1000
    gid: 1000
    groups:
    - tomcat
group:
  tomcat:
    exists: true
    gid: 1000
port:
  tcp:8080:
    listening: true
    ip:
    - 0.0.0.0
